### ISSUE TITLE
Problem with jq query

### ISSUE THREAD

**Issue by marcinkubica** [qudini/concourse-http-jq-resource#7]
Hi, hoping you could help with below issue. Following jq query works fine with jq however, getting an issue with the resource.

```
 - name: golang-http-jq-release
    type: http-jq-resource
    source:
      base_url: https://go.dev/dl/?mode=json
      jq_filter: '.[] | recurse(.files[]?) | select( .os == "linux" and .arch =="amd64") | select(.version|startswith("go1.17")).filename'


--2022-04-20 16:47:32--  https://go.dev/dl/?mode=json
Resolving go.dev... 216.239.36.21, 216.239.32.21, 216.239.34.21, ...
Connecting to go.dev|216.239.36.21|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9703 (9.5K) [application/json]
Saving to: '/tmp/echo-response'

     0K .........                                             100% 2.88M=0.003s

2022-04-20 16:47:32 (2.88 MB/s) - '/tmp/echo-response' saved [9703/9703]

parse error: Invalid numeric literal at line 2, column 0
```

linux/macos
```
❯ curl -s 'https://go.dev/dl/?mode=json' | jq '.[] | recurse(.files[]?) | select( .os == "linux" and .arch =="amd64") | select(.version|startswith("go1.17")).filename'
"go1.17.9.linux-amd64.tar.gz"
```

Cheers!
Marcin

**Comment by mohsen0** [comment]
Hi @marcinkubica 
The output of JQ filter needs to be valid JSON. I think you will be fine if you change your filter to 

```jq
.[] | recurse(.files[]?) | select( .os == "linux" and .arch =="amd64") | select(.version|startswith("go1.17"))
```
without the file name

or 
pick up the filename like this
```jq
.[] | recurse(.files[]?) | select( .os == "linux" and .arch =="amd64") | select(.version|startswith("go1.17")) | {version:.filename}

```
or 
Using the version instead of filename
```jq
.[] | recurse(.files[]?) | select( .os == "linux" and .arch =="amd64") | select(.version|startswith("go1.17")) | {version:.version}

```

**Comment by mohsen0** [comment]
I hope the suggestion worked for you, closing this ticket.

**Comment by marcinkubica** [comment]
Thanks @mohsen0, this helped.

I'm only thinking about the use case here. The output I'm looking for is a filename then used in the concourse task by wget. Effectively what I have to do is use another `jq` against `concourse-http-jq-resource`   to further extract the value I'm looking for (with -r to remove doublequotes).

Probably a feature request here would be to emulate what jq is offering on linux - ability to output jus the value with option for it to be raw (unquoted).

Cheers for the help here!
Marcin
